parameters:
#    atef_blog.example.class: atef\BlogBundle\Example

services:
#    atef_blog.example:
#        class: %atef_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
